version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-jenkins
    ports:
      - "9090:8080"
      - "50000:50000"
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # gives access to host Docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    command: >
      bash -c "apt-get update &&
               apt-get install -y git curl &&
               /usr/bin/tini -- /usr/local/bin/jenkins.sh"

volumes:
  jenkins_home:
