version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "9090:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # 👈 Mount Docker socket
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:
