apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon-devops
  template:
    metadata:
      labels:
        app: amazon-devops
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
      - name: app
        image: adityasinghlikesjiujitsu/amazon-devops-app:latest
        ports:
        - containerPort: 3000
