apiVersion: v1
kind: Service
metadata:
  name: amazon-devops-service
spec:
  selector:
    app: amazon-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
